prod:
  firstName: "John"
  lastName: "Doe"
  age: 20
ift:
  firstName: "Alex"
  lastName: "Jhonson"
  age: 44
local:
  firstName: "Fedor"
  lastName: "Ivanov"
  #jdbc local parameters:
  jdbcHostName: "localhost"
  jdbcPort: "49161"
  jdbcSid: "xe"
  jdbcUserName: "auditor"
  jdbcUserPassword: "qwe123"

